// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MtSafe.Models;

namespace MtSafe.Migrations
{
    [DbContext(typeof(MtSafeContext))]
    [Migration("20210119212004_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MtSafe.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Condition")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("ReportId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            ReportId = 1,
                            Condition = "Icy",
                            Date = new DateTime(2021, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mt. Hood",
                            Username = "doublejep"
                        },
                        new
                        {
                            ReportId = 2,
                            Condition = "Blizzard",
                            Date = new DateTime(2020, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mt. Hood",
                            Username = "RyGuy"
                        },
                        new
                        {
                            ReportId = 3,
                            Condition = "Packed Powder",
                            Date = new DateTime(2021, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Crystal Mountain",
                            Username = "2 Chains"
                        },
                        new
                        {
                            ReportId = 4,
                            Condition = "High Avalanche Danger",
                            Date = new DateTime(2021, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mt. Hood",
                            Username = "Albert"
                        },
                        new
                        {
                            ReportId = 5,
                            Condition = "Blue Bird",
                            Date = new DateTime(2021, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Location = "Mt. Bachelor",
                            Username = "Peter"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
